const { NotFoundError } = require('../utils/customErrors');

exports.errorHandler = (err, req, res, next) => {
  console.error(err.stack);

  if (err.name === 'ValidationError') {
    return res.status(400).json({ message: err.message });
  }

  if (err instanceof NotFoundError) {
    return res.status(404).json({ message: err.message });
  }

  res.status(500).json({ message: 'Something went wrong' });
};
